### ISSUE TITLE
화자 감지하는 방법 조사

### ISSUE THREAD

**Issue by 12173898** [SocialPeace/violence-detector#11]

**Comment by Minimoa** [comment]
화자 분할 방법에 대한 설명 https://dos-tacos.github.io/paper%20review/speaker_diarization/

**Comment by Minimoa** [comment]
https://github.com/yinruiqing/change_detection

**Comment by Minimoa** [comment]
화자 분할 라이브러리 https://github.com/pyannote/pyannote-audio

**Comment by Minimoa** [comment]
음성에서 의도를 파악하는 SLU http://web.donga.ac.kr/yjko/talks/SLU(Youngjoong%20Ko).pdf

**Comment by 12173898** [comment]
[오디오 녹음에서 화자 구분하기](https://cloud.google.com/speech-to-text/docs/multiple-voices?hl=ko)

**Comment by 12173898** [comment]
[화자 인식 기술 및 연구 (naver d2)](https://www.youtube.com/watch?v=HzgCnlre4EE)
